Excluding backup files from release archive, renamed overlay_root to overlay_upper, added overlay_upper_options, using overlay_options for overlay itself, and added livecd_rw to remount livecd rw.

diff --git a/hooks/overlay b/hooks/overlay
--- a/hooks/overlay
+++ b/hooks/overlay
@@ -3,7 +3,7 @@
 OVERLAY_MNT_ROOT="/run/overlay"
 
 is_overlay_root() {
-	if [[ "${overlay_root}" == "" ]]; then
+	if [[ "${overlay_upper}" == "" ]]; then
 		return 1
 	else
 		return 0
@@ -20,24 +20,27 @@ run_latehook() {
 	#mount -oremount,rw /new_root
 	mount -omove /new_root ${OVERLAY_MNT_ROOT}/ro
 
-	if [[ "${overlay_root}" != 'none' ]]; then
-		msg "Checking overlay ${overlay_root}"
-		overlay_root="$(resolve_device "${overlay_root}")"
-		if ! fsck_device "${overlay_root}"; then
-			err "Failed to fsck overlay root: ${overlay_root}"
+	if [[ "${overlay_upper}" != 'none' ]]; then
+		msg "Checking overlay ${overlay_upper}"
+		[ ! -e "${overlay_upper}" ] && overlay_upper="$(resolve_device "${overlay_upper}")"
+		if [ -b "${overlay_upper}" ] && ! fsck_device "${overlay_upper}"; then
+			err "Failed to fsck overlay root: ${overlay_upper}"
 			launch_interactive_shell --exec
 		fi
 	fi
 
-	msg "Mounting overlay ${overlay_root}"
-	if ! mount -t "${overlay_type:-auto}" -o "${overlay_options:-rw}" "${overlay_root}" ${OVERLAY_MNT_ROOT}/rw ; then
-		err "Failed to mount overlay root ${overlay_root}"
+	msg "Mounting overlay ${overlay_upper}"
+	if ! mount -t "${overlay_upper_type:-auto}" -o "${overlay_upper_options:-rw}" "${overlay_upper}" ${OVERLAY_MNT_ROOT}/rw ; then
+		err "Failed to mount overlay root ${overlay_upper}"
 		launch_interactive_shell --exec
 	fi
+
 	[ ! -d ${OVERLAY_MNT_ROOT}/rw/data ] && mkdir ${OVERLAY_MNT_ROOT}/rw/data
 	[ ! -d ${OVERLAY_MNT_ROOT}/rw/work ] && mkdir ${OVERLAY_MNT_ROOT}/rw/work
 
-	if ! mount -t overlay none /new_root -o lowerdir=${OVERLAY_MNT_ROOT}/ro,upperdir=${OVERLAY_MNT_ROOT}/rw/data,workdir=${OVERLAY_MNT_ROOT}/rw/work ; then
+	OVERLAY_OPTS="index=off,lowerdir=${OVERLAY_MNT_ROOT}/ro,upperdir=${OVERLAY_MNT_ROOT}/rw/data,workdir=${OVERLAY_MNT_ROOT}/rw/work"
+	[[ "${overlay_options}" != "" ]] && OVERLAY_OPTS="${overlay_options},${OVERLAY_OPTS}"
+	if ! mount -t overlay none /new_root -o "${OVERLAY_OPTS}" ; then
 		err "Overlay failed to mount."
 		launch_interactive_shell --exec
 	fi
